USE [master]
GO

/****** Object:  Database [sbgl ]    Script Date: 06/30/2015 08:56:46 ******/
CREATE DATABASE [sbgl ] ON  PRIMARY 
( NAME = N'sbgl', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\sbgl .mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sbgl _log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\sbgl _log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sbgl ] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sbgl ].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sbgl ] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sbgl ] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sbgl ] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sbgl ] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sbgl ] SET ARITHABORT OFF 
GO

ALTER DATABASE [sbgl ] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sbgl ] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [sbgl ] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sbgl ] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sbgl ] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sbgl ] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sbgl ] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sbgl ] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sbgl ] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sbgl ] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sbgl ] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sbgl ] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sbgl ] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sbgl ] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sbgl ] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sbgl ] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sbgl ] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sbgl ] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sbgl ] SET  READ_WRITE 
GO

ALTER DATABASE [sbgl ] SET RECOVERY FULL 
GO

ALTER DATABASE [sbgl ] SET  MULTI_USER 
GO

ALTER DATABASE [sbgl ] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sbgl ] SET DB_CHAINING OFF 
GO


