//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.5485
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSV.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WSV.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Bj {
            get {
                object obj = ResourceManager.GetObject("Bj", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Add {
            get {
                object obj = ResourceManager.GetObject("Btn_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Check {
            get {
                object obj = ResourceManager.GetObject("Btn_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Close {
            get {
                object obj = ResourceManager.GetObject("Btn_Close", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Delete {
            get {
                object obj = ResourceManager.GetObject("Btn_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Design {
            get {
                object obj = ResourceManager.GetObject("Btn_Design", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Edit {
            get {
                object obj = ResourceManager.GetObject("Btn_Edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Export {
            get {
                object obj = ResourceManager.GetObject("Btn_Export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Fresh {
            get {
                object obj = ResourceManager.GetObject("Btn_Fresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_IsCheck {
            get {
                object obj = ResourceManager.GetObject("Btn_IsCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_IsUsed {
            get {
                object obj = ResourceManager.GetObject("Btn_IsUsed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Pic {
            get {
                object obj = ResourceManager.GetObject("Btn_Pic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Preview {
            get {
                object obj = ResourceManager.GetObject("Btn_Preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Preview1 {
            get {
                object obj = ResourceManager.GetObject("Btn_Preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Print {
            get {
                object obj = ResourceManager.GetObject("Btn_Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_PrintMend {
            get {
                object obj = ResourceManager.GetObject("Btn_PrintMend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Save {
            get {
                object obj = ResourceManager.GetObject("Btn_Save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Search {
            get {
                object obj = ResourceManager.GetObject("Btn_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_start {
            get {
                object obj = ResourceManager.GetObject("Btn_start", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_Used {
            get {
                object obj = ResourceManager.GetObject("Btn_Used", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_User {
            get {
                object obj = ResourceManager.GetObject("Btn_User", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Btn_VCount {
            get {
                object obj = ResourceManager.GetObject("Btn_VCount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap But_ReName {
            get {
                object obj = ResourceManager.GetObject("But_ReName", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dl {
            get {
                object obj = ResourceManager.GetObject("dl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap h {
            get {
                object obj = ResourceManager.GetObject("h", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap main {
            get {
                object obj = ResourceManager.GetObject("main", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap s {
            get {
                object obj = ResourceManager.GetObject("s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SysLock {
            get {
                object obj = ResourceManager.GetObject("SysLock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_BPrint {
            get {
                object obj = ResourceManager.GetObject("T_BPrint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Computer {
            get {
                object obj = ResourceManager.GetObject("T_Computer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Count {
            get {
                object obj = ResourceManager.GetObject("T_Count", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_CountDay {
            get {
                object obj = ResourceManager.GetObject("T_CountDay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Lock {
            get {
                object obj = ResourceManager.GetObject("T_Lock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Add {
            get {
                object obj = ResourceManager.GetObject("T_M_Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_AS {
            get {
                object obj = ResourceManager.GetObject("T_M_AS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Base {
            get {
                object obj = ResourceManager.GetObject("T_M_Base", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Bill {
            get {
                object obj = ResourceManager.GetObject("T_M_Bill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_BillInfo {
            get {
                object obj = ResourceManager.GetObject("T_M_BillInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Cancel {
            get {
                object obj = ResourceManager.GetObject("T_M_Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Car {
            get {
                object obj = ResourceManager.GetObject("T_M_Car", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_CarCode {
            get {
                object obj = ResourceManager.GetObject("T_M_CarCode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Card {
            get {
                object obj = ResourceManager.GetObject("T_M_Card", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Check {
            get {
                object obj = ResourceManager.GetObject("T_M_Check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Count {
            get {
                object obj = ResourceManager.GetObject("T_M_Count", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_DaoZha {
            get {
                object obj = ResourceManager.GetObject("T_M_DaoZha", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_DaoZha1 {
            get {
                object obj = ResourceManager.GetObject("T_M_DaoZha1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_DaoZha2 {
            get {
                object obj = ResourceManager.GetObject("T_M_DaoZha2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_DB {
            get {
                object obj = ResourceManager.GetObject("T_M_DB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_HunWai {
            get {
                object obj = ResourceManager.GetObject("T_M_HunWai", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_IDCard {
            get {
                object obj = ResourceManager.GetObject("T_M_IDCard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Info {
            get {
                object obj = ResourceManager.GetObject("T_M_Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_LoadoMeter {
            get {
                object obj = ResourceManager.GetObject("T_M_LoadoMeter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_LogDeal {
            get {
                object obj = ResourceManager.GetObject("T_M_LogDeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_LogDefend {
            get {
                object obj = ResourceManager.GetObject("T_M_LogDefend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_LogWeight {
            get {
                object obj = ResourceManager.GetObject("T_M_LogWeight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Meter {
            get {
                object obj = ResourceManager.GetObject("T_M_Meter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Modify {
            get {
                object obj = ResourceManager.GetObject("T_M_Modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Param {
            get {
                object obj = ResourceManager.GetObject("T_M_Param", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Plan {
            get {
                object obj = ResourceManager.GetObject("T_M_Plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Power {
            get {
                object obj = ResourceManager.GetObject("T_M_Power", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Rfid {
            get {
                object obj = ResourceManager.GetObject("T_M_Rfid", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Role {
            get {
                object obj = ResourceManager.GetObject("T_M_Role", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Select {
            get {
                object obj = ResourceManager.GetObject("T_M_Select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Table {
            get {
                object obj = ResourceManager.GetObject("T_M_Table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Type {
            get {
                object obj = ResourceManager.GetObject("T_M_Type", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Users {
            get {
                object obj = ResourceManager.GetObject("T_M_Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_VCount {
            get {
                object obj = ResourceManager.GetObject("T_M_VCount", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Video {
            get {
                object obj = ResourceManager.GetObject("T_M_Video", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_Voice {
            get {
                object obj = ResourceManager.GetObject("T_M_Voice", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_M_WeiParam {
            get {
                object obj = ResourceManager.GetObject("T_M_WeiParam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Port {
            get {
                object obj = ResourceManager.GetObject("T_Port", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Port1 {
            get {
                object obj = ResourceManager.GetObject("T_Port1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_RePwd {
            get {
                object obj = ResourceManager.GetObject("T_RePwd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Rrelief {
            get {
                object obj = ResourceManager.GetObject("T_Rrelief", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Select {
            get {
                object obj = ResourceManager.GetObject("T_Select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap T_Weight {
            get {
                object obj = ResourceManager.GetObject("T_Weight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_BaseInfo {
            get {
                object obj = ResourceManager.GetObject("Tool_BaseInfo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Count {
            get {
                object obj = ResourceManager.GetObject("Tool_Count", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Defend {
            get {
                object obj = ResourceManager.GetObject("Tool_Defend", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_HardWare {
            get {
                object obj = ResourceManager.GetObject("Tool_HardWare", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Help {
            get {
                object obj = ResourceManager.GetObject("Tool_Help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Log {
            get {
                object obj = ResourceManager.GetObject("Tool_Log", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Plan {
            get {
                object obj = ResourceManager.GetObject("Tool_Plan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Search {
            get {
                object obj = ResourceManager.GetObject("Tool_Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_System {
            get {
                object obj = ResourceManager.GetObject("Tool_System", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Users {
            get {
                object obj = ResourceManager.GetObject("Tool_Users", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tool_Weight {
            get {
                object obj = ResourceManager.GetObject("Tool_Weight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Top_Left {
            get {
                object obj = ResourceManager.GetObject("Top_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Top_Pan_Left {
            get {
                object obj = ResourceManager.GetObject("Top_Pan_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Top_Right {
            get {
                object obj = ResourceManager.GetObject("Top_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon wucheng {
            get {
                object obj = ResourceManager.GetObject("wucheng", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap z {
            get {
                object obj = ResourceManager.GetObject("z", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
